baseURL = 'https://KeithFrost.github.io'
languageCode = 'en-us'
title = 'forays'
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"

disableKinds = ["taxonomy"]

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "monokai"

[permalinks]
blog = "/:year/:month/:day/:slug/"

[languages]
[languages.en]
languageName ="English"
title = "forays"
[languages.en.params]
description = "explorations in science, mathematics, art, and technology"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "monokai"


prism_syntax_highlighting = true